name: salah
description: "A comprehensive Islamic learning and prayer app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.3.0
  quran: ^1.2.2
  adhan: ^2.0.0-nullsafety.2
  flutter_qiblah: ^2.2.0
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.1.0
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.18
  table_calendar: ^3.0.9
  intl: ^0.18.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_tts: ^3.8.5
  flutter_compass: ^0.8.0
  groq_sdk: ^1.0.2
  hijri: ^3.0.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  cloud_firestore: ^4.15.5
  timezone: ^0.9.2
  firebase_core: ^2.25.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/audio/
    - assets/audio/duas/
    - assets/quran/
    - assets/hadith/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade-Regular.ttf
        - asset: assets/fonts/Scheherazade-Bold.ttf
          weight: 700
